let array = [
    {id:0,text:"Estados Unidos", size:250, imagem:"https://static.mundoeducacao.uol.com.br/mundoeducacao/2022/05/bandeira-estados-unidos.jpg"},
    {id:1,text:"Índia", size:120, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/280px-Flag_of_India.svg.png"},
    {id:2,text:"Brasil", size:89, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/2000px-Flag_of_Brazil.svg.png"},
    {id:3,text:"Suécia", size:89, imagem:"https://png.pngtree.com/thumb_back/fw800/background/20240305/pngtree-silken-swirls-sweden-flag-for-national-day-image_15635927.jpg"},
    {id:4,text:"Japão", size:89, imagem:"https://s4.static.brasilescola.uol.com.br/be/2022/11/bandeira-do-japao.jpg"},
    {id:5,text:"China", size:89, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/255px-Flag_of_the_People%27s_Republic_of_China.svg.png"},
    {id:6,text:"Coreia do Sul", size:89, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/300px-Flag_of_South_Korea.svg.png"},
    {id:7,text:"Coreia do Norte", size:89, imagem:"https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg"},
    {id:8,text:"Alemanha", size:89, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/2560px-Flag_of_Germany.svg.png"},
    {id:9,text:"França", size:89, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/2560px-Flag_of_France.svg.png"},
    {id:10,text:"Itália", size:89, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/2560px-Flag_of_Italy.svg.png"},
    {id:11,text:"Argentina", size:89, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/2560px-Flag_of_Argentina.svg.png"},
    {id:12,text:"México", size:89, imagem:"https://s4.static.brasilescola.uol.com.br/be/2022/10/bandeira-do-mexico.jpg"},
    {id:13,text:"Rússia", size:89, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/2560px-Flag_of_Russia.svg.png"},
    {id:14,text:"Austrália", size:45, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/2560px-Flag_of_Australia.svg.png"},
    {id:15,text:"África do Sul", size:60, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/2560px-Flag_of_South_Africa.svg.png"},
    {id:16,text:"Canadá", size:40, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/305px-Flag_of_Canada_%28Pantone%29.svg.png"},
    {id:17,text:"Espanha", size:30, imagem:"https://static.mundoeducacao.uol.com.br/mundoeducacao/2022/01/bandeira-da-espanha.jpg"},
    {id:18,text:"Turquia", size:40, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/2560px-Flag_of_Turkey.svg.png"},
    {id:19,text:"Egito", size:89, imagem:"https://geo5.net/imagens/Bandeira-do-Egito.png"},
    {id:20,text:"Indonésia", size:60, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/2560px-Flag_of_Indonesia.svg.png"},
    {id:21,text:"Paquistão", size:40, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/2560px-Flag_of_Pakistan.svg.png"},
    {id:22,text:"Nova Zelândia",  size:40, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/2560px-Flag_of_New_Zealand.svg.png"},
    {id:23,text:"Noruega",  size:42, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/2560px-Flag_of_Norway.svg.png"},
    {id:24,text:"Dinamarca",  size:55, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/2560px-Flag_of_Denmark.svg.png"},
    {id:25,text:"Grécia",  size:60, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/2560px-Flag_of_Greece.svg.png"},
    {id:26,text:"Polônia",  size:60, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/2560px-Flag_of_Poland.svg.png"},
    {id:27,text:"Portugal",  size:42, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/2560px-Flag_of_Portugal.svg.png"},
    {id:28,text:"Colômbia", size:60, imagem:"https://static.significados.com.br/foto/bnadeira-da-colombia-significados.jpg"},
    {id:29,text:"Vietnã", size:50, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/2560px-Flag_of_Vietnam.svg.png"},
    {id:30,text:"Chile", size:40, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/2560px-Flag_of_Chile.svg.png"},
    {id:31,text:"Malásia", size:50, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/2560px-Flag_of_Malaysia.svg.png"},
    {id:32,text:"Singapura", size:40, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/255px-Flag_of_Singapore.svg.png"},
    {id:33,text:"Israel", size:45, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/640px-Flag_of_Israel.svg.png"},
    {id:34,text:"Irã", size:45, imagem:"https://s4.static.brasilescola.uol.com.br/be/2022/11/bandeira-ira1.jpg"},
    {id:35,text:"Afeganistão", size:50, imagem:"https://geo5.net/imagens/bandeira-do-afeganistao-2000px.png"},
    {id:36,text:"Bangladesh", size:55, imagem:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/640px-Flag_of_Bangladesh.svg.png"},
    {id:37,text:"Arábia Saudita", size:55, imagem:"https://s3.static.brasilescola.uol.com.br/be/2022/10/bandeira-arabia-saudita1.jpg"}
]


export default array;